language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t johny2000wub/docker-react -f Dockerfile.dev .

scripts:
  - docker run johny2000uwb/docker-react -- --coverage